config/routes.rb
routedef = Proc.new do |options|
  resources :pastes, options do
    member do
      get :download
    end
  end
end

# new paste can be only created on a project
routedef.call :except => :new

scope '/projects/:project_id', :as => 'per_project' do
  routedef.call({})
end

app/models/paste.rb
# redmine_pastebin -- A real pastebin plugin for Redmine.
#
# Copyright (C) 2011  Alex Shuglin <ash@commandprompt.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

require "digest/sha1"

class Paste < ActiveRecord::Base
  unloadable # really?

  belongs_to :project
  belongs_to :author, :class_name => 'User'

  scope :for_project, -> (project) {
    where({ :project_id => project })
  }

  scope :secure, -> {
    where("access_token IS NOT NULL")
  }

  scope :expired, -> {
    where("expires_at <= current_timestamp")
  }

  scope :unexpired, -> {
    where("expires_at IS NULL OR expires_at > current_timestamp")
  }

  #
  # * Restrict to projects where the user has a role allowing to view
  #   pastes.
  #
  # * Restrict to specific project, if given.
  #
  # * Admin users should be able to see all pastes, even secure ones.
  #
  # * An ordinary user can see a secure paste only if he has authored it.
  #
  # * Never show expired pastes even to an admin.
  #
  scope :visible, -> (user=nil, options={}) {
    user ||= User.current

    s = where(Project.allowed_to_condition(user, :view_pastes, options)).joins(:project)
    unless user.admin?
      s = s.where(["access_token IS NULL OR author_id = ?", user.id])
    end
    s.unexpired
  }

  #
  # The default scope limits what's exposed by event providers below.
  #
  # The use of block is important so that current user is evaluated
  # every time inside the visible scope as opposed to being captured
  # at the time of Paste class load.
  #
  default_scope { visible }

  #
  # We need to use exclusive scope to be able to specify a user other
  # than the current one.  Otherwise the default scope will be in
  # conflict by overriding the user.
  #
  def self.visible_to(user, options={})
    unscoped do
      Paste.visible(user, options)
    end
  end

  acts_as_searchable :columns => ["#{table_name}.title", "#{table_name}.text"],
    :scope => preload(:project)

  acts_as_event :title => Proc.new{ |o| o.title },
    :url => Proc.new{ |o| { :controller => 'pastes', :action => 'show',
      :id => o.to_param } }

  acts_as_activity_provider :scope => preload([:project, :author]),
    :author_key => :author_id

  def title
    return if new_record?
    t = super
    t.present? ? t : "Paste ##{id}"
  end

  def description
    short_text
  end

  SHORT_TEXT_LIMIT = 100

  def short_text
    if text.length < SHORT_TEXT_LIMIT
      text
    else
      text[0..SHORT_TEXT_LIMIT] + "..."
    end
  end

  def secure?
    access_token.present?
  end
  alias_method :secure, :secure?

  def to_param
    secure? ? access_token : id.to_s
  end

  def secure!
    # update_attribute won't work as access_token isn't listed as
    # `accessible'
    self.secure = true
    save!
  end

  def secure=(value)
    self.access_token = value ? make_access_token : nil
  end

  def self.secure_id?(id)
    # assume SHA1 hexdigest
    id =~ /^[0-9a-f]{40}$/
  end

  def self.find_by_secure_id(id)
    unscoped do
      find_by_access_token(id)
    end
  end

  def expired?
    expires_at.present? && expires_at <= Time.now
  end

  def expire_in(seconds)
    self.expires_at = Time.now + seconds
  end

  def self.wipe_all_expired
    unscoped do
      Paste.expired.delete_all
    end
  end

  private

  def make_access_token
    Digest::SHA1.hexdigest("#{self.inspect}@#{Time.now.to_f}")
  end
end

app/controllers/pastes_controller.rb
# redmine_pastebin -- A real pastebin plugin for Redmine.
#
# Copyright (C) 2011  Alex Shuglin <ash@commandprompt.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

class PastesController < ApplicationController
  unloadable

  include PastesHelper

  default_search_scope :pastes

  before_action :find_paste_and_project, :authorize

  accept_atom_auth :index

  def index
    @limit = per_page_option

    @pastes_count = @pastes.count
    @pastes_pages = Paginator.new(self, @pastes_count, @limit, params[:page])
    @offset ||= @pastes_pages.current.offset
    @pastes = @pastes.all.order(:created_on).offset(@offset).limit(@limit)

    respond_to do |format|
      format.html { render :layout => false if request.xhr? }
      format.atom { render_feed(@pastes, :title => (@project ? @project.name : Setting.app_title) + ": " + l(:label_paste_plural)) }
    end
  end

  def show
  end

  def download
    send_data @paste.text, :filename => pastebin_filename(@paste),
      :type => pastebin_mime_type(@paste),
      :disposition => 'attachment'
  end

  def new
    @paste = @project.pastes.build
  end

  def edit
  end

  def create
    @paste = @project.pastes.build(paste_params)
    @paste.author = User.current
    @paste.secure = (params[:paste][:secure] == "1")
    @paste.expire_in(params[:paste][:expires].to_i) if params[:paste][:expires].to_i > 0
    if @paste.save
      flash[:notice] = l(:notice_paste_created)
      redirect_to @paste
    else
      render(params[:fork].blank? ? :new : :edit)
    end
  end

  def update
    if params[:fork].present?
      create
    else
      if @paste.update(paste_params)
        flash[:notice] = l(:notice_paste_updated)
        redirect_to @paste
      else
        render :edit
      end
    end
  end

  def destroy
    @paste.destroy
    flash[:notice] = l(:notice_paste_destroyed)
    redirect_to :action => "index", :project_id => params[:project_id]
  end

  private

  def paste_params
    params.require(:paste).permit(:title, :lang, :text)
  end

  def find_paste_and_project
    @project = Project.find(params[:project_id]) if params[:project_id].present?
    @pastes = Paste.visible_to(User.current, :project => @project)

    if params[:id].present?
      if Paste.secure_id?(params[:id])
        @paste = Paste.find_by_secure_id(params[:id]) || raise(ActiveRecord::RecordNotFound)
        @pastes = nil
      else
        @paste = @pastes.find(params[:id])
      end
      @project ||= @paste.project
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/pastes_helper.rb
# redmine_pastebin -- A real pastebin plugin for Redmine.
#
# Copyright (C) 2011  Alex Shuglin <ash@commandprompt.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

module PastesHelper
  PASTEBIN_LANGS =  ["Plain Text", "Apache Config", "Bash", "C", "C++", "CSS", "CoffeeScript",
                     "Diff", "Git","Go","HAML", "JSON", "Java", "JavaScript", "Markdown",
                     "Markup", "Nginx","PHP", "Perl", "Python", "Ruby", "SQL", "XML", "YAML"]

  # This maps pretty language/syntax name to identifier that PrismJS
  # can understand.  If a language is not mapped, unchanged name is
  # assumed for the scanner.
  PASTEBIN_SCANNERS_MAP = {
    'Plain Text' => 'Plaintext',
    'Markup' => 'markup',
    'CSS' => 'css',
    'Apache Config' => 'apacheconf',
    'Bash' => 'bash',
    'CoffeeScript' => 'coffeescript',
    'Git' => 'git',
    'Go' => 'go',
    'HAML' => 'haml',
    'JSON' => 'json',
    'Markdown' => 'markdown',
    'Nginx' => 'nginx',
    'Perl' => 'perl',
    'C' => 'c',
    'Java' => 'java',
    'JavaScript' => 'javascript',
    'Python' => 'python',
    'Ruby' => 'ruby',
    'PHP' => 'php',
    'SQL' => 'sql',
    'XML' => 'xml',
    'Diff' => 'diff',
    'YAML' => 'yaml',
    'C++' => 'cpp'
  }

  PASTEBIN_MIME_TYPES_MAP = {
    'Plain Text' => 'text/plain',
    'C' => 'text/x-c',
    'Ruby' => 'text/x-ruby',
    'PHP' => 'text/x-php',
    'XML' => 'application/xml',
    'python' => 'text/x-python',
    'markdown' => 'text/x-markdown',
    'bash' => 'text/x-shellscript',
    'coffeescript' => 'application/vnd.coffeescript'
  }

  PASTEBIN_FILE_SUFFIX_MAP = {
    'Plain Text' => 'txt',
    'Plaintext' => 'txt',
    'git' => 'txt',
    'markup' => 'txt',
    'C++' => 'cpp',
    'JavaScript' => 'js',
    'Python' => 'py',
    'Ruby' => 'rb',
    'ruby' => 'rb',
    'python' => 'py',
    'coffeescript' => 'coffee',
    'bash' => 'sh',
    'markdown' => 'md',
    'perl' => 'pl',
    'javascript' => 'js',
    'nginx' => 'conf',
    'apacheconf' => 'conf'

  }

  PASTEBIN_EXPIRATION_CHOICES = [[:never, 0], [:an_hour, 1.hour], [:a_day, 1.day]]

  def pastebin_lang_to_scanner(lang)
    PASTEBIN_SCANNERS_MAP[lang] || lang
  end

  def pastebin_language_name(lang)
    PASTEBIN_SCANNERS_MAP.invert[lang] || lang
  end

  def pastebin_language_choices
    PASTEBIN_LANGS.map { |v| [v, pastebin_lang_to_scanner(v)] }
  end

  def pastebin_expiration_choices
    PASTEBIN_EXPIRATION_CHOICES.map { |x| [translate(:"paste_expires_in_#{x.first}"), x.last] }
  end

  def pastebin_filename_suffix(paste)
    PASTEBIN_FILE_SUFFIX_MAP[paste.lang] || paste.lang.downcase
  end

  def pastebin_filename(paste)
    paste.title + "." + pastebin_filename_suffix(paste)
  end

  def pastebin_mime_type(paste)
    PASTEBIN_MIME_TYPES_MAP[paste.lang] || "application/octet-stream"
  end

  def highlighted_content_for_paste(paste)
    content_tag :pre do
      content_tag :code, :class => "language-#{pastebin_lang_to_scanner(paste.lang)} line-numbers" do
        paste.text
      end
    end
  end

  def paste_timestamp(paste)
    content_tag :span, :class => "timestamp" do
      paste.created_on.to_s(:db)
    end
  end

  def url_to_paste(action, paste = nil)
    { :controller => "pastes", :action => action,
      :id => paste, :project_id => @project }
  end

  def link_to_paste(paste)
    link_to(paste.title, paste)
  end

  def edit_paste_link(paste, title = l(:button_edit))
    link_to_if_authorized(title, url_to_paste("edit", paste),
                          :class => "icon icon-edit")
  end

  def delete_paste_link(paste, title = l(:button_delete))
    link_to_if_authorized(title, url_to_paste("destroy", paste),
                          :class => "icon icon-del",
                          :method => :delete,
                          data: {confirm: l(:text_paste_delete_confirmation)})
  end

  def download_paste_link(paste, title = l(:button_download))
    link_to(title, url_to_paste("download", paste),
            :class => "icon icon-save")
  end

  def manage_paste_links(paste)
    [edit_paste_link(paste),
     delete_paste_link(paste),
     download_paste_link(paste)].join("\n").html_safe
  end

  def link_to_all_pastes
    link_to(l(:label_paste_view_all), url_to_paste("index"),
            :class => "icon icon-multiple")
  end

  def link_to_new_paste
    link_to_if_authorized(l(:label_paste_new), url_to_paste("new"),
                          :class => "icon icon-add")
  end
end

app/views/pastes/_authorship.html.erb
<%= authoring paste.created_on, paste.author %>.

<% if paste.updated_on != paste.created_on %>
  <%= l(:label_updated_time, time_tag(paste.updated_on)).html_safe %>.
<% end %>
<% if paste.expires_at.present? %>
 <span style="color: red;"><%= l(:label_paste_expires_at) %> <%= format_time(paste.expires_at) %></span>
<% end %>

app/views/pastes/_sidebar.html.erb
<% content_for :sidebar do %>
<h3><%=l :label_paste_plural %></h3>
<p><%= link_to_new_paste %></p>
<p><%= link_to_all_pastes if @paste %></p>
<% end %>

app/views/pastes/edit.html.erb
<% html_title @paste.title %>

<h2><%= l(:label_paste_edit, :link => link_to_paste(@paste)).html_safe %></h2>

<p>
<%= render :partial => "authorship", :locals => { :paste => @paste } %>
</p>

<%= labelled_form_for @paste,
   :url => { :action => "update", :id => @paste },
   :html => { :method => :put } do |f| %>
<div class="box tabular">
  <%= hidden_field_tag "fork" %>

  <p><%= f.text_field :title, :label => :field_paste_title %></p>
  <p><%= f.select :lang, pastebin_language_choices,
         :label => :field_paste_lang %></p>
  <p><%= f.text_area :text, :label => :field_paste_text,
         :rows => 25, :cols => 80 %></p>
</div>

<%= l(:text_paste_update_or_make_new,
      :update => f.submit(l(:button_paste_update)),
      :make_new => submit_tag(l(:button_paste_make_new),
                              :onclick => "$('#fork').val('yes')")).html_safe %>
<% end %>

app/views/pastes/index.html.erb
<% title = l(:label_paste_plural) %>
<% html_title title %>

<% content_for :header_tags do %>
<style type="text/css">
.paste {
  margin-bottom: 2.5em;
}
.paste .author, .paste .actions {
  float: right;
}
.paste .box {
  margin-bottom: 2px;
}
</style>
<% end %>

<h2><%=h title %></h2>

<% if @pastes.empty? %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% else %>
<% @pastes.each do |paste| %>
  <% cache("paste-short-#{paste.id}-#{User.current.language}", skip_digest: true) do %>
  <div class="paste">
    <%= link_to_paste paste %>&nbsp;&ndash;
    <% unless @project %>
      <%= link_to_project paste.project %>&nbsp;&ndash;
    <% end %>
    <div class="author">
      <%= render :partial => "authorship", :locals => { :paste => paste } %>
    </div>
    <%= pastebin_language_name(paste.lang) %>
    <div class="box">
      <pre><%=h paste.short_text %></pre>
    </div>
    <div class="actions">
      <%= manage_paste_links(paste) %>
    </div>
  </div>
  <% end %>
<% end %>

<p class="pagination">
  <%= pagination_links_full @pastes_pages, @pastes_count %>
</p>
<% end %>

<% other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => { :project_id => @project,
        :key => User.current.rss_key } %>
<% end %>

<%= render "sidebar" if @project %>

app/views/pastes/new.html.erb
<% html_title l(:label_paste_new) %>

<h2><%=l :label_paste_new %></h2>

<%= labelled_form_for @paste,
    :url => { :action => "create", :project_id => @paste.project.id } do |f| %>
<div class="box tabular">
  <p><%= f.text_field :title, :label => :field_paste_title %></p>
  <p><%= f.check_box :secure, :label => :field_paste_secure %>
     <%=l :paste_security_hint %></p>
  <p><label for="paste_expires"><%=l :field_paste_expires %></label>
   <%= select_tag 'paste[expires]',
       options_from_collection_for_select(pastebin_expiration_choices,
                                          :last, :first) %></p>
  <p><%= f.select :lang, pastebin_language_choices,
         :label => :field_paste_lang %></p>
  <p><%= f.text_area :text, :label => :field_paste_text,
         :rows => 25, :cols => 80 %></p>
</div>
<%= f.submit l(:button_paste_submit) %>
<% end %>

app/views/pastes/show.html.erb
<% content_for :header_tags do %>
<%= stylesheet_link_tag 'scm' %>
<%= stylesheet_link_tag 'prism', :plugin => "redmine_pastebin" %>
<%= javascript_include_tag 'prism', :plugin => "redmine_pastebin" %>
<% end %>

<% html_title @paste.title %>

<h2><%=h @paste.title %></h2>

<p>
<%= l(:label_paste_link_here, :link => link_to(paste_url(@paste), @paste)).html_safe %>
</p>

<p>
<%= render :partial => "authorship", :locals => { :paste => @paste } %><br>
<%=l :label_paste_syntax, :lang => pastebin_language_name(@paste.lang) %>
</p>

<div class="paste">
<%= highlighted_content_for_paste(@paste) %>
</div>

<p>
<%= manage_paste_links(@paste) %>
</p>

<%= render "sidebar" if @project %>